# This file was generated by GoReleaser. DO NOT EDIT.
cask "gbr" do
  name "gbr"
  desc "Switch git branch interactively using arrow keys"
  homepage "https://github.com/Kadrian/gbr"
  version "2.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gbr"

  on_macos do
    on_intel do
      url "https://github.com/Kadrian/gbr/releases/download/v#{version}/gbr_#{version}_darwin_amd64.tar.gz"
      sha256 "136c32ec62e825363977386d797cd25365357468a884c2ee3420d379ce947b5f"
    end
    on_arm do
      url "https://github.com/Kadrian/gbr/releases/download/v#{version}/gbr_#{version}_darwin_arm64.tar.gz"
      sha256 "bed313df348ac1e070ed55d0571718ac14d71826cf8616c8eed55f2eead2731a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Kadrian/gbr/releases/download/v#{version}/gbr_#{version}_linux_amd64.tar.gz"
      sha256 "34b9d976af9967c9eed3dc2b98bc2473b0ca9c7d721a4b1cea33e7737c2ef9c0"
    end
    on_arm do
      url "https://github.com/Kadrian/gbr/releases/download/v#{version}/gbr_#{version}_linux_arm64.tar.gz"
      sha256 "ff8b7b6fd209bf0d0812cb03533fae6b70d39716261b16a69d1ffec609577177"
    end
  end

  # No zap stanza required
end
