# This file was generated by GoReleaser. DO NOT EDIT.
cask "gbr" do
  name "gbr"
  desc "Switch git branch interactively using arrow keys"
  homepage "https://github.com/Kadrian/gbr"
  version "2.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gbr"

  on_macos do
    on_intel do
      url "https://github.com/Kadrian/gbr/releases/download/v#{version}/gbr_#{version}_darwin_amd64.tar.gz"
      sha256 "e5b58c3561f5b7260ad4f16ac104423cbfcbea99ebe47bdf9fcb34a6b9a75071"
    end
    on_arm do
      url "https://github.com/Kadrian/gbr/releases/download/v#{version}/gbr_#{version}_darwin_arm64.tar.gz"
      sha256 "5f6ab690f1870019e8ddffd7fefed1c42603438140ba281898b5cff9a6957969"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Kadrian/gbr/releases/download/v#{version}/gbr_#{version}_linux_amd64.tar.gz"
      sha256 "cc3df5d9f6222b40cab69dc29ad0dd8b9fdb61f228807d24d3bfbeda7f502fc7"
    end
    on_arm do
      url "https://github.com/Kadrian/gbr/releases/download/v#{version}/gbr_#{version}_linux_arm64.tar.gz"
      sha256 "347b1b4015884cf03fe0d46e1fea324714662b978708efce94b72b9744d30213"
    end
  end

  # No zap stanza required
end
