# This file was generated by GoReleaser. DO NOT EDIT.
cask "gbr" do
  name "gbr"
  desc "Switch git branch interactively using arrow keys"
  homepage "https://github.com/Kadrian/gbr"
  version "2.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gbr"

  on_macos do
    on_intel do
      url "https://github.com/Kadrian/gbr/releases/download/v#{version}/gbr_#{version}_darwin_amd64.tar.gz"
      sha256 "69736724c0c91ac8b972b7a692d45833bde3b8cdbe1b020b0a336f5aa24ef83d"
    end
    on_arm do
      url "https://github.com/Kadrian/gbr/releases/download/v#{version}/gbr_#{version}_darwin_arm64.tar.gz"
      sha256 "78d076b589bc7cc2b35891efafc603beaf0ed924632a124aecb7333aeb001c5d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Kadrian/gbr/releases/download/v#{version}/gbr_#{version}_linux_amd64.tar.gz"
      sha256 "6caaebc89eb154feab499b8faf4471d2363c6038712ae2e723965703275a3efc"
    end
    on_arm do
      url "https://github.com/Kadrian/gbr/releases/download/v#{version}/gbr_#{version}_linux_arm64.tar.gz"
      sha256 "d028d7f06f9aae56a56c56ddc8e312d0eb2c3e52fd4b6474f7770115bd34e4e4"
    end
  end

  # No zap stanza required
end
